export const RESTAURANTS = [
  {
    id: 1,
    name: "Jollibee",
    category: 'food',
    image: require('../assets/images/restaurant/Jollibee.png'),
    address: "123 Đường ABC, Quận 1",
    rating: 4.7,
    menu: [],
  },
  {
    id: 2,
    name: "KFC",
    category: 'food',
    image: require('../assets/images/restaurant/KFC.jpg'),
    address: "456 Đường XYZ, Quận 3",
    rating: 4.5,
    menu: [],
  },
  {
    id: 3,
    name: "Texas Chicken",
    category: 'food',
    image: require('../assets/images/restaurant/Texas.png'),
    address: "456 Đường XYZ, Quận 3",
    rating: 4.5,
    menu: [],
  },
  {
    id: 4,
    name: "Phúc Long",
    category: 'coffee',
    image: require('../assets/images/restaurant/phuclong.png'),
    address: "456 Đường XYZ, Quận 7",
    rating: 4.6,
    menu: [],
  },
  {
    id: 5,
    name: "Highlands Coffee",
    category: ['coffee','milktea'],
    image: require('../assets/images/restaurant/highland.png'),
    address: "456 Đường XYZ, Quận 7",
    rating: 4.6,
    menu: [],
  },
  {
    id: 6,
    name: "Maycha",
    category: 'milktea',
    image: require('../assets/images/restaurant/maycha.png'),
    address: "456 Đường XYZ, Quận 7",
    rating: 4.6,
    menu: [],
  },
];