// Data thuần - dùng chung cho cả Web và Mobile
export const RESTAURANTS_DATA = [
  {
    id: 1,
    name: "Jollibee",
    category: 'fastfood',
    imageName: 'Jollibee.png',
    address: "123 Đường ABC, Quận 1",
    rating: 4.7,
    menu: [],
    isFeatured: true,
    coordinates: {
      latitude: 10.7769,
      longitude: 106.7009
    }
  },
  {
    id: 2,
    name: "KFC",
    category: 'fastfood',
    imageName: 'KFC.jpg',
    address: "456 Đường XYZ, Quận 3",
    rating: 4.5,
    menu: [],
    isFeatured: true,
    coordinates: {
      latitude: 10.7829,
      longitude: 106.7009
    }
  },
  {
    id: 3,
    name: "Texas Chicken",
    category: 'fastfood',
    imageName: 'Texas.png',
    address: "456 Đường XYZ, Quận 3",
    rating: 4.5,
    menu: [],
    isFeatured: false,
    coordinates: {
      latitude: 10.7889,
      longitude: 106.7009
    }
  },
  {
    id: 4,
    name: "Phúc Long",
    category: ['coffee','milktea'],
    imageName: 'phuclong.png',
    address: "456 Đường XYZ, Quận 7",
    rating: 4.6,
    menu: [],
    isFeatured: true,
    coordinates: {
      latitude: 10.7329,
      longitude: 106.7209
    }
  },
  {
    id: 5,
    name: "Highlands Coffee",
    category: ['coffee','milktea'],
    imageName: 'highland.png',
    address: "456 Đường XYZ, Quận 7",
    rating: 4.6,
    menu: [],
    isFeatured: true,
    coordinates: {
      latitude: 10.7429,
      longitude: 106.7309
    }
  },
  {
    id: 6,
    name: "Maycha",
    category: 'milktea',
    imageName: 'maycha.png',
    address: "456 Đường XYZ, Quận 7",
    rating: 4.6,
    menu: [],
    isFeatured: false,
  },
  {
    id: 7,
    name: "Lotteria",
    category: "fastfood",
    imageName: 'lotteria.png',
    address: "22 Trần Hưng Đạo, Quận 5",
    rating: 4.3,
    menu: [],
    isFeatured: true,
  },
  {
    id: 8,
    name: "Cơm Tấm Cali",
    category: "rice",
    imageName: "cali.png",
    address: "18 Lý Tự Trọng, Quận 1",
    rating: 4.6,
    menu: [],
    isFeatured: false,
  },
  {
    id: 20,
    name: "Cơm Tấm Sà Bì Chưởng",
    category: "rice",
    imageName: "sabichuong.jpg",
    address: "20 Trần Bình Trọng, Quận 5",
    rating: 4.6,
    menu: [],
    isFeatured: true,
  },
  {
    id: 9,
    name: "The Coffee House",
    category: "coffee",
    imageName: "TCH.jpg",
    address: "23 Nguyễn Thị Minh Khai, Quận 3",
    rating: 4.5,
    menu: [],
    isFeatured: true,
  },
  {
    id: 10,
    name: "Bún Bò Huế 3A",
    category: "noodle",
    imageName: "Bunbohue3A.jpg",
    address: "78 Điện Biên Phủ, Quận Bình Thạnh",
    rating: 4.4,
    menu: [],
    isFeatured: false,
  },
  {
    id: 11,
    name: "Phở Hòa",
    category: "noodle",
    imageName: "PhoHoa.png",
    address: "260 Pasteur, Quận 3",
    rating: 4.8,
    menu: [],
    isFeatured: true,
  },
  {
    id: 12,
    name: "Chay Bồ Đề",
    category: "vegetable",
    imageName: "chaybode.jpg",
    address: "12 Nguyễn Văn Trỗi, Phú Nhuận",
    rating: 4.6,
    menu: [],
    isFeatured: false,
  },
  {
    id: 13,
    name: "Pizza Hut",
    category: "fastfood",
    imageName: "pizzahut.jpg",
    address: "11 Hai Bà Trưng, Quận 1",
    rating: 4.4,
    menu: [],
    isFeatured: false,
  },
  {
    id: 14,
    name: "Sushi Kei",
    category: "asia",
    imageName: "sushikei.png",
    address: "Vincom Đồng Khởi, Quận 1",
    rating: 4.7,
    menu: [],
    isFeatured: false,
  },
  {
    id: 15,
    name: "Cơm Niêu Sài Gòn",
    category: "rice",
    imageName: "comnieusaigon.png",
    address: "75 Lê Văn Sỹ, Quận 3",
    rating: 4.6,
    menu: [],
    isFeatured: true,
  },
  {
    id: 16,
    name: "Sukiya",
    category: ["asia","rice"],
    imageName: "sukiya.png",
    address: "Vincom Đồng Khởi, Quận 1",
    rating: 4.7,
    menu: [],
    isFeatured: true,
  },
  {
    id: 17,
    name: "Nhà Hàng Chay Mandala",
    category: "vegetable",
    imageName: "mandala.jpg",
    address: "101 Lý Chính Thắng, Quận 3",
    rating: 4.7,
    menu: [],
    isFeatured: true,
  },
  {
    id: 18,
    name: "Bánh tằm Thầy Ba",
    category: "asia",
    imageName: "thayba.jpg",
    address: "101 Lý Chính Thắng, Quận 3",
    rating: 4.7,
    menu: [],
    isFeatured: true,
  },
  {
    id: 19,
    name: "Hồng Trà Ngô Gia",
    category: "milktea",
    imageName: "ngogia.jpg",
    address: "101 Lý Chính Thắng, Quận 3",
    rating: 4.7,
    menu: [],
    isFeatured: true,
  },
];
